[package]
name = "rtiow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.25.6"
piston_window = "0.132.0"
rand = {version = "0.9.0"}
rayon = "1.10.0"
indicatif = {version = "0.17.11", features = ["rayon"]}
paste = "1.0.15"